// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeEntries.Api.Persistence;

namespace TimeEntries.Api.Migrations
{
    [DbContext(typeof(TimeEntriesDbContext))]
    [Migration("20210611124031_CreateTimeEntriesDB")]
    partial class CreateTimeEntriesDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimeEntries.Api.Persistence.Models.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique id of the entry.")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2")
                        .HasComment("Timestamp from.");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasComment("Id of the linked project.");

                    b.Property<DateTime>("Until")
                        .HasColumnType("datetime2")
                        .HasComment("Timestamp until.");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("Id of the linked user.");

                    b.HasKey("Id");

                    b.ToTable("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
