# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  users-api:
    image: users-api
    build:
      context: .
      dockerfile: src/Users.Api/Dockerfile
    ports:
      - 5001:443
      - 50010:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SQL_CONNECTION_STRING=Server=users-db,5002;Database=UsersDb;User Id=sa;Password=yourStrong(!)Password
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/aspnetapp.pfx
    volumes:
      - ${HOME}/.aspnet/https/aspnetapp.pfx:/app/https/aspnetapp.pfx:ro
    depends_on:
      - users-db

  users-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 5002:1433
    environment:
      - SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y